### ISSUE TITLE
Blazor Server - Action Button in DataGrid

### ISSUE THREAD

**Issue by cellero** [volosoft/lepton-theme#12]
The action items (Edit and Delete) do not render correctly.
1.  When there is only 1 item in the grid the Delete option does not show:
![image](https://user-images.githubusercontent.com/15643712/179153031-157b453a-457b-48a3-853e-701fb53c471f.png)

2. When there are 2 or more and the last item is chosen, the pop up appears above the Action button.
This is confusing as it is not clear which row is being actioned:
![image](https://user-images.githubusercontent.com/15643712/179153236-8099101b-099e-4df4-a737-1b8c62d29322.png)

**Comment by ismcagdas** [comment]
@cellero did you try this on open source ABP templates ?

**Comment by cellero** [comment]
Commercial user - created with ABP Suite.  ABP v5.3.2

**Comment by ismcagdas** [comment]
@enisn as far as I remember, we fixed this problem, right ? Could you check it with the latest version ?

**Comment by cellero** [comment]
I've tested this again today for Blazor Server on ABP Suite Commercial 6.0.0-rc.1 and the issue remains:
![image](https://user-images.githubusercontent.com/15643712/181144966-18521c91-2233-4731-b780-59793065bf8a.png)

    <PackageReference Include="Volo.Abp.AspNetCore.Mvc.UI.Theme.LeptonX" Version="1.0.0-rc.1" />
    <PackageReference Include="Volo.Abp.AspNetCore.Components.Server.LeptonXTheme" Version="1.0.0-rc.1" />

**Comment by ismcagdas** [comment]
@cellero thanks, I have created an internal issue, so I'm closing this one. If you find any issues realted to LeptonX theme, you can create the issues on https://github.com/abpframework/abp/.
